-- AlterTable
ALTER TABLE `order` ADD COLUMN `totalOrderAmount` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `orderitem` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `currentPrice` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalAmount` INTEGER NOT NULL DEFAULT 0;
